---
title: 坑爹的配环境经历
date: 2017-02-07 02:00:52
tags:
- spark
- anaconda
---
最近突然想玩玩spark。
在`Ubuntu 16.04`中装好java，配好spark，由于懒得配python科学计算环境，于是直接下载了anaconda4.3.0（写文章时的最新版）。装好以后发现这个版本的anaconda自带python3.6。
而我的`spark 2.1.0 bin hadoop 2.7`最高兼容到python3.5。
于是，本打算用anaconda-navigator创建个python3.5的环境，结果又一次成功的被坑到
```
Traceback (most recent call last):
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 250, in save_config
    os.makedirs(data_dir)
  File "/home/lijing/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/lijing/.continuum/anaconda-client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lijing/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 87, in start_app
    window = run_app(splash)
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 42, in run_app
    window = MainWindow(splash=splash)
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 204, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 131, in __init__
    data_directory=CHANNELS_PATH,
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/home/lijing/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /home/lijing/.continuum/anaconda-client: Permission denied
```
大家感受一下，看着头大有木有，还是用命令行把python3.5的环境搭建起来吧。
`conda create -n py3.5 python=3.5 matplotlib numpy`
下载速度慢的。。。正常，就在这时候，宝宝惊喜的发现清华大学有anaconda的镜像，*看看人家的大学*。
根据`https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/`的说明
`conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/`，削个苹果的时间就全都装好了。
最后，`source activate py3.5`，大功告成。
最后的最后，来看看上面的报错，看起来是`/home/lijing/.continuum/anaconda-client`这个文件夹的权限有问题，这才想起来在装anaconda的时候手贱多敲了个sudo，心情不爽，怒删`~/.continuum`，图形界面就可以成功打开了。。。